#'summaryLM
#'
#'summaryLM is a function used to print a summary of the results of the fitted model by using LM().
#'It mimics the printed output of the build-in method using summary(lm()).
#'@param result the returned list of outputs by using LM() to fit the linear regression model
#'
#'@examples
#'##Note: the examples are generated by R's default dataset iris
#'
#'## fit the simple linear regression model
#'LM_result = LM(Sepal.Width ~ Sepal.Length, data = iris)
#'summaryLM(LM_result) ## obtain the summary of the fitted model
#'
#'## fit the simple linear regression model
#'LM_result = LM(Sepal.Width ~ Sepal.Length, data = iris, intercept = FALSE) # omiting intercept
#'summaryLM(LM_result)
#'
#'## fit the multiple linear regression model
#'LM_result = LM(Sepal.Width ~ Sepal.Length + Petal.Length, data = iris)
#'summaryLM(LM_result)
#'
#'## fit the multiple linear regression model with interaction
#'LM_result = LM(Sepal.Width ~ Sepal.Length * Petal.Length, data = iris)
#'summaryLM(LM_result)
#'
#'## fit the linear regression model with only interaction terms
#'LM_result = LM(Sepal.Width ~ I(Sepal.Length * Petal.Length), data = iris)
#'summaryLM(LM_result)
#'
#'## Note: the examples are generated by R's default dataset mtcars
#'
#'## fit the simple linear regression model
#'LM_result = LM(drat ~ wt, data = mtcars)
#'summaryLM(LM_result) ## obtain the summary of the fitted model
#'
#'## fit the simple linear regression model
#'LM_result = LM(drat ~ wt, data = mtcars, intercept = FALSE) # omiting intercept
#'summaryLM(LM_result)
#'
#'## fit the multiple linear regression model
#'LM_result = LM(drat ~ wt + qsec, data = mtcars)
#'summaryLM(LM_result)
#'
#'## fit the multiple linear regression model with interaction
#'LM_result = LM(drat ~ wt * qsec, data = mtcars)
#'summaryLM(LM_result)
#'
#'## fit the linear regression model with only interaction terms
#'LM_result = LM(drat ~ I(wt * qsec), data = mtcars)
#'summaryLM(LM_result)
#'
#'
#'@export
#'
summaryLM = function(result) {
  ## format the residuals information
  summaryLM_residuals = quantile(result$residuals)
  names(summaryLM_residuals) =
    c("Min", "1Q", "Median", "3Q", "Max")

  ## format the table includes estimates of beta coefficients, standard error, t value, and p-value
  ## label the significance
  LM_pval = result$coefficients_df[, 4]
  sig_star = ifelse (LM_pval < 0.001, '***',
                     ifelse (LM_pval < 0.01, '** ',
                             ifelse(
                               LM_pval < 0.05, '*  ',
                               ifelse(LM_pval < 0.1, '.  ', '')
                             )))
  LM_pval = ifelse(LM_pval < 2.2e-16, "< 2.2e-16", LM_pval)
  coefficients_df = result$coefficients_df
  coefficients_df[, 4] = LM_pval
  coefficients_table = cbind(coefficients_df, sig_star)
  names(coefficients_table) = c("Estimate", "Std. Error", "t value", "Pr(>|t|)", "")

  ## format the overall F-test
  Fpvalue = ifelse(result$`F.p-value` < 2.2e-16, "< 2.2e-16", result$`F.p-value`)

  ## start to print all the formatted outputs from above ##
  ## mimic the printed summary from summary(lm()) in R ##
  cat("Call: ", result$call, ' ',  "Residuals: ", sep = '\n')
  print(summaryLM_residuals)

  cat("\nCoefficients: \n")
  print(coefficients_table)
  cat("---\n")

  Signif.codes =
    "Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1"
  cat(Signif.codes, "\n\n")

  summary_LM =
    paste(
      c(
        "Residual standard error: ",
        result$sigma,
        " on ",
        result$df.residual,
        " degrees of freedom \nMultiple R-Squared: ",
        result$r.squared,
        ", Adjusted R-squared: ",
        result$adj.r.squared,
        "\nF-Statistic: ",
        result$fstatistic[1],
        " on ",
        result$fstatistic[2],
        " and ",
        result$fstatistic[3],
        " DF, p-value: ",
        Fpvalue
      ),
      collapse = ''
    )
  cat(summary_LM)
}
